title: ujamstudio
description: Study notes, projects, troubleshooting, and things I learn.
url: ""
baseurl: ""

markdown: kramdown
highlighter: rouge

permalink: /posts/:title/
future: true

collections:
  knowledge:
    output: true
    permalink: /knowledge/:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "knowledge"
    values:
      layout: knowledge
