title: ujamstudio
description: Study notes, projects, troubleshooting, and things I learn.
url: ""
baseurl: ""

markdown: kramdown
highlighter: rouge

permalink: /posts/:title/

collections_dir: .

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
